version: '3.8'

services:
  plataforma_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: club_deportivo_frontend
    ports:
      - "8080:80"
    restart: unless-stopped
