import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faHouse,
  faUsers,
  faFutbol,
  faTrophy,
  faCalendarDays,
  faChartLine,
  faMoneyBillWave,
  faFileInvoiceDollar,
  faCreditCard,
  faChartPie,
  faBoxesStacked,
  faCartShopping,
  faWarehouse,
  faPeopleGroup,
  faIdCard,
  faUserShield,
  faRightFromBracket,
  faBars,
  faXmark,
  faPlus,
  faPenToSquare,
  faTrash,
  faEye,
  faMagnifyingGlass,
  faFilter,
  faChevronLeft,
  faChevronRight,
  faCheck,
  faCircleExclamation,
  faTriangleExclamation,
  faCircleInfo,
  faBasketballBall,
  faTableTennisPaddleBall,
  faPersonSwimming,
  faHandFist,
  faArrowUp,
  faArrowDown,
  faCircle,
  faCashRegister,
  faClipboardList,
  faStar,
  faEnvelope,
  faPhone,
  faLocationDot,
  faCalendar,
  faClock,
  faFlag,
  faMedal,
  faShirt,
  faChevronDown,
  faChevronUp,
  faGear,
  faCircleCheck,
  faSpinner,
  faReceipt,
  faBullseye,
  faSitemap,
  faBuilding,
  faPencil,
  faHandPointer,
  faClipboardUser,
  faSun,
  faMoon,
  faCalendarCheck,
  faCalendarXmark,
  faArrowRight,
  faArrowLeft,
  faFloppyDisk,
  faUserTie,
  faRocket,
  faChessBoard,
  faEyeSlash,
  faTimes,
  faCalendarDay,
  faHeartPulse, faRulerVertical, faWeightScale, faStethoscope, faLungs, faBandage, faQrcode, faFileSignature, faChartSimple,
  faBook, faCheckCircle, faTags, faRotateRight, faBan, faUser
} from '@fortawesome/free-solid-svg-icons'

import {
  faStar as farStar,
} from '@fortawesome/free-regular-svg-icons'

library.add(
  faHouse, faUsers, faFutbol, faTrophy, faCalendarDays,
  faChartLine, faMoneyBillWave, faFileInvoiceDollar, faCreditCard,
  faChartPie, faBoxesStacked, faCartShopping, faWarehouse,
  faPeopleGroup, faIdCard, faUserShield, faRightFromBracket,
  faBars, faXmark, faPlus, faPenToSquare, faTrash,
  faEye, faMagnifyingGlass, faFilter, faChevronLeft, faChevronRight,
  faCheck, faCircleExclamation, faTriangleExclamation, faCircleInfo,
  faBasketballBall, faTableTennisPaddleBall, faPersonSwimming, faHandFist,
  faArrowUp, faArrowDown, faCircle, faCashRegister, faClipboardList,
  faStar, farStar, faEnvelope, faPhone, faLocationDot, faCalendar, faClock,
  faFlag, faMedal, faShirt, faChevronDown, faChevronUp, faGear,
  faCircleCheck, faSpinner, faReceipt, faBullseye,
  faSitemap, faBuilding, faPencil, faHandPointer, faClipboardUser,
  faSun, faMoon,
  faCalendarCheck, faCalendarXmark, faArrowRight, faArrowLeft,
  faFloppyDisk, faUserTie, faRocket,
  faChessBoard, faEyeSlash, faTimes, faCalendarDay,
  faHeartPulse, faRulerVertical, faWeightScale, faStethoscope, faLungs, faBandage, faQrcode, faFileSignature, faChartSimple,
  faBook, faCheckCircle, faTags, faRotateRight, faBan, faUser
)
